# Generated by Django 5.2.13 on 2026-04-25 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def completar_datos_resolucion(apps, schema_editor):
    Ticket = apps.get_model("tickets", "Ticket")
    for ticket in Ticket.objects.all().iterator():
        updated = []
        if ticket.resuelto_en and not ticket.resuelto_por_id:
            ticket.resuelto_por_id = ticket.asignado_a_id or ticket.respondido_por_id
            updated.append("resuelto_por")
        if ticket.estado == "cerrado" and not ticket.cerrado_en:
            ticket.cerrado_en = ticket.actualizado_en
            updated.append("cerrado_en")
        if ticket.estado == "cerrado" and not ticket.cerrado_por_id:
            ticket.cerrado_por_id = ticket.creado_por_id if ticket.cerrado_por_usuario else (ticket.asignado_a_id or ticket.respondido_por_id)
            updated.append("cerrado_por")
        if updated:
            ticket.save(update_fields=updated)


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_articulobaseconocimiento_ticket_asignado_a_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="cerrado_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="cerrado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets_cerrados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="resuelto_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets_resueltos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(completar_datos_resolucion, migrations.RunPython.noop),
    ]
